M48
; DRILL file {KiCad 6.0.11-2627ca5db0~126~ubuntu22.04.1} date Sun 05 May 2024 03:56:38 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-05T15:56:38-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11-2627ca5db0~126~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.300
%
G90
G05
T1
X103.82Y-76.43
X103.82Y-82.21
T2
X136.69Y-67.52
X136.69Y-82.51
T0
M30
